### GET status
GET http://localhost:3000/status

### GET blocks
GET http://localhost:3000/blocks/3

### GET blocks next
GET http://localhost:3000/blocks/next

### POST block
POST http://localhost:3000/blocks
content-type: application/json

{
    "hash": "",
    "index": 2,
    "data": "Block 3",
    "previousHash": "1870d225593655ee12b3db4c6b38d6e4260a7d3283d009d5437e3fcfc9a6a373"
}

### GET transaction
GET http://localhost:3000/transactions

### GET transaction
GET http://localhost:3000/transactions/9ded61e0d318637a239caa2a48afa8f04e52c73cf557215f1a80ddc07a13c9e6

### POST transaction
POST http://localhost:3000/transactions
content-type: application/json

{
    "hash": "",
    "data": "tx3"
}