import { login } from "@/services/Web3Service.";
import Head from "next/head";
import { ChangeEvent, useEffect, useState } from "react";

export default function Mint() {
  const [quantity, setQuantity] = useState(1);
  const [wallet, setWallet] = useState("");
  const [message, setMessage] = useState("");

  useEffect(() => {
    const wallet = localStorage.getItem("wallet");
    if (wallet) {
      setWallet(wallet);
    }
  }, []);

  function onQuantityChange(event: ChangeEvent<HTMLInputElement>): void {
    setQuantity(parseInt(event.target.value));
  }

  function btnMintClick(): void {
    setMessage("Minting...");
    alert("Minting...");
    setMessage("");
  }

  function btnLoginClick(): void {
    setMessage("Logging In...");
    login()
      .then((wallet) => {
        setWallet(wallet);
        localStorage.setItem("wallet", wallet);
        setMessage("");
      })
      .catch((error) => {
        setMessage(error.message);
      });
  }

  function btnLogoutClick(): void {
    setMessage("Logging Out...");
    setWallet("");
    localStorage.removeItem("wallet");
    setMessage("");
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Mint Page</h1>
        <p>
          {wallet ? (
            <>
              <a
                href={`${process.env.OPENSEA_URL}/${wallet}`}
                target="_blank"
                rel="noopener noreferrer"
              >
                {wallet}
              </a>
              <button id="btnLogout" onClick={btnLogoutClick}>
                Logout
              </button>
            </>
          ) : (
            <button id="btnLogin" onClick={btnLoginClick}>
              Login
            </button>
          )}
        </p>
        {wallet && (
          <p>
            <label htmlFor="">
              Quantity:
              <input
                type="number"
                id="quantity"
                value={quantity}
                onChange={onQuantityChange}
              />
            </label>
            <button id="btnMint" onClick={btnMintClick}>
              Mint
            </button>
          </p>
        )}

        <p>{message}</p>
      </main>
    </>
  );
}
