### Get Health check
GET http://localhost:3001/

### Get residents by wallet
GET http://localhost:3001/residents/0xF357fBCE8c00da01eeF37670413F5f2c2aB64191
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ3YWxsZXQiOiIweGYzNTdmYmNlOGMwMGRhMDFlZWYzNzY3MDQxM2Y1ZjJjMmFiNjQxOTEiLCJzZWNyZXQiOiIweDY4M2Y5ZTUyN2RiY2M2OTljNmM2YWMxZWVmNzU3ZThlY2JmN2Y0YWJkNTQ1N2ZmMjU1ZDQ1N2RjZTBhMjAzMDUwMDg0NWE4OTIyMjgwZTk2ZWVkZDkzOGRhMTI5YjhlODIwMmMxNTI3MDdhM2UyNTdjMWM4ODhhMDgyZWVhY2NjMWMiLCJ0aW1lc3RhbXAiOjE2OTM1OTA5MzcxMDQsInByb2ZpbGUiOiIyIiwiaWF0IjoxNjkzNTkwOTQzLCJleHAiOjE2OTM1OTI3NDN9.L_5lMJa1vKpz1cWT0px6NXIkpPFPf2Ge2IIb0VvdMso

### Post resident
POST http://localhost:3001/residents/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ3YWxsZXQiOiIweGYzNTdmYmNlOGMwMGRhMDFlZWYzNzY3MDQxM2Y1ZjJjMmFiNjQxOTEiLCJzZWNyZXQiOiIweDY4M2Y5ZTUyN2RiY2M2OTljNmM2YWMxZWVmNzU3ZThlY2JmN2Y0YWJkNTQ1N2ZmMjU1ZDQ1N2RjZTBhMjAzMDUwMDg0NWE4OTIyMjgwZTk2ZWVkZDkzOGRhMTI5YjhlODIwMmMxNTI3MDdhM2UyNTdjMWM4ODhhMDgyZWVhY2NjMWMiLCJ0aW1lc3RhbXAiOjE2OTM1OTA5MzcxMDQsInByb2ZpbGUiOiIyIiwiaWF0IjoxNjkzNTkwOTQzLCJleHAiOjE2OTM1OTI3NDN9.L_5lMJa1vKpz1cWT0px6NXIkpPFPf2Ge2IIb0VvdMso

{
    "wallet": "0xF357fBCE8c00da01eeF37670413F5f2c2aB64191",
    "name": "Manager",
    "profile": "2",
    "phone": "+5575988223930",
    "email": "fabio_net1000@hotmail.com"
}

### Delete resident
DELETE http://localhost:3001/residents/123

### Patch resident
PATCH http://localhost:3001/residents/0xF357fBCE8c00da01eeF37670413F5f2c2aB64191
Content-Type: application/json

{
    "name": "Condominium Manager"
}